package com.proyecto.sicecuador.datos.administracion;

import com.proyecto.sicecuador.Constantes;
import com.proyecto.sicecuador.modelos.administracion.Modelo;
import com.proyecto.sicecuador.repositorios.administracion.IModeloRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
@Component
@Order(1)
public class ModeloData implements ApplicationRunner {
    @Autowired
    private IModeloRepository rep;

    @Override
    public void run(ApplicationArguments args) throws Exception {
        Optional<Modelo> ant=rep.findById((long) 1);
        if (!ant.isPresent()){
            List<Modelo> modelos=new ArrayList<>();
            Modelo modelo=new Modelo("AMORTIZACION", "amortizacion", "amortizacion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("AUXILIAR","auxiliar", "auxiliar", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("BANCO","banco", "banco", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("BODEGA","bodega", "bodega", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("BODEGA PRODUCTO ","bodega_producto", "bodegaproducto", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CARACTERISTICA","caracteristica", "caracteristica", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CATEGORIA DEL CLIENTE","categoria_cliente", "categoriacliente", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CELULAR", "celular", "celular", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CELULAR DEL AUXILIAR","celular_auxiliar", "celularauxiliar", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CHEQUE","cheque", "cheque", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CLIENTE", "cliente", "cliente", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("COMPENSACION","compensacion", "compensacion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CORREO","correo", "correo", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CORREO DEL AUXILIAR","correo_auxiliar", "correoauxiliar", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CREDITO","credito", "credito", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CREDITO DE AMORTIZACION","credito_amortizacion", "creditoamortizacion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("CUENTA PROPIA","cuenta_propia", "cuenta_propia", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("DEPOSITO","deposito", "deposito", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("DIRECCION","direccion", "direccion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("EGRESO","egreso", "egreso", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("EMPRESA","empresa", "empresa", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("ESTABLECIMIENTO","establecimiento", "establecimiento", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("ESTADO CIVIL","estado_civil", "estadocivil", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("FACTURA","factura", "factura", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("FACTURA DETALLE","factura_detalle", "facturadetalle", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("FINACIAMIENTO","financiamiento", "financiamiento", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("FORMA DE PAGO","forma_pago", "formapago", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("FRANQUICIA DE TARJETA", "franquicia_tarjeta", "franquiciatarjeta", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("GENERO","genero", "genero", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("GRUPO DE CLIENTE","grupo_cliente", "grupocliente", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("GRUPO DE PRODUCTO","grupo_producto", "grupoproducto", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("GUIA DE REMISION","guia_remision", "guiaremision", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("IMPUESTO","impuesto", "impuesto", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("KARDEX","kardex", "kardex", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("MEDIDA","medida", "medida", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("OPERADOR DE TARJETA","operador_tarjeta", "operadortarjeta", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("ORIGEN DE INGRESO","origen_ingreso", "origeningreso", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PARAMETRO","parametro", "parametro", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PEDIDO","pedido", "pedido", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PERFIL","perfil", "perfil", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PERMISO","permiso", "permiso", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PLAZO DE CREDITO","plazo_credito", "plazocredito", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PRECIO","precio", "precio", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PRODUCTO","producto", "producto", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PROFORMA","proforma", "proforma", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PROVEEDOR","proveedor", "proveedor", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("PUNTO DE VENTA","punto_venta", "puntoventa", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("RANGO DE CREDITO","rango_crediticio", "rangocrediticio", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("RECAUDACION","recaudacion", "recaudacion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("RETENCION DE CLIENTE","retencion_cliente", "retencioncliente", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("RETENCION DE VENTA","retencion_venta", "retencionventa", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("RETENCION DE VENTA DETALLE","retencion_venta_detalle", "retencionventadetalle", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("SESION","sesion", "sesion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TARJETA DE CREDITO","tarjeta_credito", "tarjetacredito", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TARJETA DEBITO","tarjeta_debito", "tarjetadebito", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TELEFONO","telefono", "telefono", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TELEFONO AUXILIAR","telefono_auxiliar", "telefonoauxiliar", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TIPO DE COMPROBANTE","tipo_comprobante", "tipocomprobante", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TIPO DE CONTRIBUYENTE","tipo_contribuyente", "tipocontribuyente", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TIPO DE PAGO","tipo_pago", "tipopago", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TIPO DE PRODUCTO","tipo_producto", "tipoproducto", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TIPO DE RETENCION","tipo_retencion", "tiporetencion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TRANSFERENCIA","transferencia", "transferencia", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("TRANSPORTISTA","transportista", "transportista", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("UBICACION","ubicacion", "ubicacion", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("USUARIO","usuario", "usuario", Constantes.activo);
            modelos.add(modelo);
            modelo=new Modelo("VEHICULO DE TRANSPORTE","vehiculo_transporte", "vehiculotransporte", Constantes.activo);
            modelos.add(modelo);
            rep.saveAll(modelos);
        }
    }

}
