package com.proyecto.vision.datos.inventario;

import com.proyecto.vision.Constantes;
import com.proyecto.vision.modelos.compra.Proveedor;
import com.proyecto.vision.modelos.configuracion.Impuesto;
import com.proyecto.vision.modelos.inventario.*;
import com.proyecto.vision.modelos.usuario.Empresa;
import com.proyecto.vision.repositorios.inventario.IProductoRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

@Component
@Order(43)
@Profile({"dev","prod"})
public class ProductoData implements ApplicationRunner {
    @Autowired
    private IProductoRepository rep;
        @Override
        public void run(ApplicationArguments args) throws Exception {
            Optional<Producto> ant=rep.findById((long) 1);
            if (!ant.isPresent()) {
                List<Producto> productos = new ArrayList<>();
                //PRODUCTOS PARA EMPRESA 1
                productos.add(new Producto("PRO012307000001", "CELULARES", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(1), new TipoGasto(1), new Impuesto(1), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO012307000002", "REFRIGERADOR", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(1), new TipoGasto(1), new Impuesto(2), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO012307000003", "TELEVISOR", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(1), new TipoGasto(1), new Impuesto(1), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO012307000004", "CAMAS", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(1), new TipoGasto(1), new Impuesto(2), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO012307000005", "LADRILLOS", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(1), new TipoGasto(1), new Impuesto(3), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO012307000006", "AVIONES", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(1), new TipoGasto(1), new Impuesto(4), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                //SERVICIOS PARA EMPRESA 1
                productos.add(new Producto("PRO012307000007", "SERVICIO INFORMATICO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(2), new GrupoProducto(1), new TipoGasto(1), new Impuesto(2), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO012307000008", "INTERESES CORRIENTES", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(2), new GrupoProducto(2), new TipoGasto(1), new Impuesto(2), new Medida(1), new Proveedor(1), new Empresa(1), Collections.emptyList(), Collections.emptyList()));
                //PRODUCTOS PARA EMPRESA 2
                productos.add(new Producto("PRO022308000001","AGUA TESALIA 500 ML", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(16), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000002","CERV. CORONA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(17), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000003","CERV. PILSENER 1 LT", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(18), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000004","CERV.CLUB 1 LT", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(19), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000005","CEV ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(20), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000006","CEV CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(21), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000007","CEV CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(22), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000008","CEV CUADRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(23), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000009","CEV DE CUERO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(24), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000010","CEV DE OREJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(25), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000011","CEV DE POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(26), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000012","CEV DE TODITO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(27), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000013","CEV DE TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(28), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000014","CEV LIGTH", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(29), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000015","CEV MAX", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(30), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000016","CEV MIXT. ATUN+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(31), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000017","CEV MIXT. CHICHARRON+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(32), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000018","CEV MIXT. CUERO+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(33), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000019","CEV MIXT. CUERO+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(34), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000020","CEV MIXT. CUERO+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(35), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000021","CEV MIXT. CUERO+MOLLEJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(36), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000022","CEV MIXT. CUERO+OREJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(37), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000023","CEV MIXT. CUERO+POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(38), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000024","CEV MIXT. CUERO+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(39), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000025","CEV MIXT. MOLLEJA+POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(40), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000026","CEV MIXT. OREJA+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(41), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000027","CEV MIXT. OREJA+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(42), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000028","CEV MIXT. OREJA+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(43), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000029","CEV MIXT. OREJA+MOLLEJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(44), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000030","CEV MIXT. OREJA+POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(45), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000031","CEV MIXT. OREJA+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(46), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000032","CEV MIXT. POLLO+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(47), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000033","CEV MIXT. POLLO+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(48), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000034","CEV MIXT. POLLO+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(49), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000035","CEV MIXT. POLLO+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(50), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000036","CEV TRIM. CUERO+CHICHARRON+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(51), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000037","CEV TRIM. CUERO+MOLLEJA+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(52), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000038","CEV TRIM. CUERO+OREJA+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(53), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000039","CEV TRIM. CUERO+OREJA+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(54), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000040","CEV TRIM. CUERO+OREJA+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(55), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000041","CEV TRIM. CUERO+OREJA+MOLLEJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(56), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000042","CEV TRIM. CUERO+OREJA+POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(57), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000043","CEV TRIM. CUERO+OREJA+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(58), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000044","CEV TRIM. CUERO+POLLO+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(59), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000045","CEV TRIM. CUERO+POLLO+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(60), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000046","CEV TRIM. CUERO+POLLO+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(61), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000047","CEV TRIM. CUERO+POLLO+MOLLEJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(62), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000048","CEV TRIM. CUERO+POLLO+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(63), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000049","CEV TRIM. CUERO+TROMPA+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(64), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000050","CEV TRIM. OREJA+CHICHARRON+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(65), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000051","CEV TRIM. OREJA+MOLLEJA+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(66), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000052","CEV TRIM. OREJA+POLLO+ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(67), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000053","CEV TRIM. OREJA+POLLO+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(68), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000054","CEV TRIM. OREJA+POLLO+MOLLEJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(69), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000055","CEV TRIM. OREJA+POLLO+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(70), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000056","CEV TRIM. OREJA+TROMPA+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(71), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000057","CEV TRIM. POLLO+CHICHARRON+CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(72), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000058","CEV TRIM. POLLO+MOLLEJA+TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(73), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000059","CEV TRIM. POLLO+OREJA+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(74), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000060","CEV TRIM. POLLO+TROMPA+CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(75), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000061","FUZE TEA 1LT", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(76), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000062","FUZE TEA 500ML", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(77), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000063","GASEOSA LITRO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(78), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000064","GASEOSA MEDIANA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(79), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000065","GASEOSAS DESECHABLE", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(80), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000066","GUITIG", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(81), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000067","JUGO DE COCO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(82), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000068","JUGO DE NARANJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(83), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000069","JUGO DE TAMARINDO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(84), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000070","MED CEV MIXT. CUERO+OREJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(85), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000071","MED CEV MIXT. CUERO+POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(86), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000072","MED CEV MIXT. OREJA+POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(87), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000073","MED CEV. CUERO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(88), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000074","MED CEV. LIGHT", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(89), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000075","MED CEV. OREJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(90), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000076","MED CEV. POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(91), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000077","POR. CHIFLE", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(92), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000078","POR. DE AGUACATE", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(93), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000079","POR. DE ATUN", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(94), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000080","POR. DE CAMARON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(95), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000081","POR. DE CHICHARRON", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(96), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000082","POR. DE CHOCHOS", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(97), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000083","POR. DE CUERO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(98), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000084","POR. DE MOLLEJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(99), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000085","POR. DE OREJA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(100), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000086","POR. DE POLLO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(101), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000087","POR. DE TOSTADO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(102), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000088","POR. DE TROMPA", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(103), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));
                productos.add(new Producto("PRO022308000089","VOLQUETERO", Constantes.no, Constantes.estadoActivo, new CategoriaProducto(1), new GrupoProducto(104), new TipoGasto(2), new Impuesto(1), new Medida(35), new Proveedor(3), new Empresa(2) , Collections.emptyList(), Collections.emptyList()));

                rep.saveAll(productos);
            }
    }
}
