package com.proyecto.sicecuador.repositorios.datos.administracion;

import com.proyecto.sicecuador.modelos.administracion.Modelo;
import com.proyecto.sicecuador.repositorios.interf.administracion.IModeloRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class ModeloData implements ApplicationRunner {
    @Autowired
    private IModeloRepository rep;

    @Override
    public void run(ApplicationArguments args) throws Exception {
        Optional<Modelo> ant=rep.findById((long) 1);
        if (!ant.isPresent()){
            List<Modelo> modelos=new ArrayList<>();
            Modelo modelo=new Modelo("amortizacion");
            modelos.add(modelo);
            modelo=new Modelo("auxiliar");
            modelos.add(modelo);
            modelo=new Modelo("banco");
            modelos.add(modelo);
            modelo=new Modelo("bodega");
            modelos.add(modelo);
            modelo=new Modelo("bodega_producto");
            modelos.add(modelo);
            modelo=new Modelo("caracteristica");
            modelos.add(modelo);
            modelo=new Modelo("categoria_cliente");
            modelos.add(modelo);
            modelo=new Modelo("celular");
            modelos.add(modelo);
            modelo=new Modelo("celular_auxiliar");
            modelos.add(modelo);
            modelo=new Modelo("cheque");
            modelos.add(modelo);
            modelo=new Modelo("cliente");
            modelos.add(modelo);
            modelo=new Modelo("compensacion");
            modelos.add(modelo);
            modelo=new Modelo("correo");
            modelos.add(modelo);
            modelo=new Modelo("correo_auxiliar");
            modelos.add(modelo);
            modelo=new Modelo("credito");
            modelos.add(modelo);
            modelo=new Modelo("credito_amortizacion");
            modelos.add(modelo);
            modelo=new Modelo("cuenta_propia");
            modelos.add(modelo);
            modelo=new Modelo("deposito");
            modelos.add(modelo);
            modelo=new Modelo("direccion");
            modelos.add(modelo);
            modelo=new Modelo("egreso");
            modelos.add(modelo);
            modelo=new Modelo("empresa");
            modelos.add(modelo);
            modelo=new Modelo("establecimiento");
            modelos.add(modelo);
            modelo=new Modelo("estado_civil");
            modelos.add(modelo);
            modelo=new Modelo("factura");
            modelos.add(modelo);
            modelo=new Modelo("factura_caracteristica");
            modelos.add(modelo);
            modelo=new Modelo("factura_detalle");
            modelos.add(modelo);
            modelo=new Modelo("financiamiento");
            modelos.add(modelo);
            modelo=new Modelo("forma_pago");
            modelos.add(modelo);
            modelo=new Modelo("franquicia_tarjeta");
            modelos.add(modelo);
            modelo=new Modelo("genero");
            modelos.add(modelo);
            modelo=new Modelo("grupo_cliente");
            modelos.add(modelo);
            modelo=new Modelo("grupo_producto");
            modelos.add(modelo);
            modelo=new Modelo("guia_remision");
            modelos.add(modelo);
            modelo=new Modelo("impuesto");
            modelos.add(modelo);
            modelo=new Modelo("kardex");
            modelos.add(modelo);
            modelo=new Modelo("medida");
            modelos.add(modelo);
            modelo=new Modelo("operador_tarjeta");
            modelos.add(modelo);
            modelo=new Modelo("origen_ingreso");
            modelos.add(modelo);
            modelo=new Modelo("parametro");
            modelos.add(modelo);
            modelo=new Modelo("pedido");
            modelos.add(modelo);
            modelo=new Modelo("perfil");
            modelos.add(modelo);
            modelo=new Modelo("permiso");
            modelos.add(modelo);
            modelo=new Modelo("plazo_credito");
            modelos.add(modelo);
            modelo=new Modelo("precio");
            modelos.add(modelo);
            modelo=new Modelo("producto");
            modelos.add(modelo);
            modelo=new Modelo("proforma");
            modelos.add(modelo);
            modelo=new Modelo("proveedor");
            modelos.add(modelo);
            modelo=new Modelo("punto_venta");
            modelos.add(modelo);
            modelo=new Modelo("rango_crediticio");
            modelos.add(modelo);
            modelo=new Modelo("recaudacion");
            modelos.add(modelo);
            modelo=new Modelo("retencion_cliente");
            modelos.add(modelo);
            modelo=new Modelo("retencion_venta");
            modelos.add(modelo);
            modelo=new Modelo("retencion_venta_detalle");
            modelos.add(modelo);
            modelo=new Modelo("sesion");
            modelos.add(modelo);
            modelo=new Modelo("tarjeta_credito");
            modelos.add(modelo);
            modelo=new Modelo("tarjeta_debito");
            modelos.add(modelo);
            modelo=new Modelo("telefono");
            modelos.add(modelo);
            modelo=new Modelo("telefono_auxiliar");
            modelos.add(modelo);
            modelo=new Modelo("tipo_comprobante");
            modelos.add(modelo);
            modelo=new Modelo("tipo_contribuyente");
            modelos.add(modelo);
            modelo=new Modelo("tipo_pago");
            modelos.add(modelo);
            modelo=new Modelo("tipo_producto");
            modelos.add(modelo);
            modelo=new Modelo("tipo_retencion");
            modelos.add(modelo);
            modelo=new Modelo("transferencia");
            modelos.add(modelo);
            modelo=new Modelo("transportista");
            modelos.add(modelo);
            modelo=new Modelo("ubicacion");
            modelos.add(modelo);
            modelo=new Modelo("usuario");
            modelos.add(modelo);
            modelo=new Modelo("vehiculo_transporte");
            modelos.add(modelo);
            rep.saveAll(modelos);
        }
    }

}
